window.NFT_LINKS = [
    'https://fragment.com/gift/lovecandle-12838',
    'https://fragment.com/gift/lovecandle-6716',
    'https://fragment.com/gift/lovecandle-3045',
    'https://fragment.com/gift/lovecandle-11747',
    'https://fragment.com/gift/lovecandle-8870',
    'https://fragment.com/gift/lovecandle-288',
    'https://fragment.com/gift/lovecandle-1805',
    'https://fragment.com/gift/lovecandle-11971',
    'https://fragment.com/gift/lovecandle-32',
    'https://fragment.com/gift/lovecandle-5243',
    'https://fragment.com/gift/lovecandle-3664',
    'https://fragment.com/gift/lovecandle-8523',
    'https://fragment.com/gift/lovecandle-7427',
    'https://fragment.com/gift/lovecandle-6776',
    'https://fragment.com/gift/lovecandle-5714',
    'https://fragment.com/gift/petsnake-10724',
    'https://fragment.com/gift/petsnake-12609',
    'https://fragment.com/gift/petsnake-28109',
    'https://fragment.com/gift/petsnake-55108',
    'https://fragment.com/gift/petsnake-37139',
    'https://fragment.com/gift/petsnake-33299',
    'https://fragment.com/gift/petsnake-29275',
    'https://fragment.com/gift/petsnake-233',
    'https://fragment.com/gift/petsnake-28064',
    'https://fragment.com/gift/petsnake-22987',
    'https://fragment.com/gift/petsnake-75423',
    'https://fragment.com/gift/petsnake-6347',
    'https://fragment.com/gift/petsnake-28119',
    'https://fragment.com/gift/petsnake-28095',
    'https://fragment.com/gift/petsnake-28092',
    'https://fragment.com/gift/preciouspeach-1982',
    'https://fragment.com/gift/preciouspeach-994',
    'https://fragment.com/gift/preciouspeach-1834',
    'https://fragment.com/gift/preciouspeach-1763',
    'https://fragment.com/gift/preciouspeach-1750',
    'https://fragment.com/gift/preciouspeach-1983',
    'https://fragment.com/gift/preciouspeach-2061',
    'https://fragment.com/gift/preciouspeach-1578',
    'https://fragment.com/gift/preciouspeach-1843',
    'https://fragment.com/gift/preciouspeach-1440',
    'https://fragment.com/gift/preciouspeach-1482',
    'https://fragment.com/gift/preciouspeach-78',
    'https://fragment.com/gift/preciouspeach-35',
    'https://fragment.com/gift/preciouspeach-1549',
    'https://fragment.com/gift/preciouspeach-1862',
    'https://fragment.com/gift/santahat-19779',
    'https://fragment.com/gift/santahat-12343',
    'https://fragment.com/gift/santahat-923',
    'https://fragment.com/gift/santahat-27652',
    'https://fragment.com/gift/santahat-20393',
    'https://fragment.com/gift/santahat-17442',
    'https://fragment.com/gift/santahat-40524',
    'https://fragment.com/gift/santahat-762',
    'https://fragment.com/gift/santahat-54050',
    'https://fragment.com/gift/santahat-42769',
    'https://fragment.com/gift/santahat-37689',
    'https://fragment.com/gift/santahat-36971',
    'https://fragment.com/gift/santahat-3326',
    'https://fragment.com/gift/santahat-33018',
    'https://fragment.com/gift/santahat-27700',
    'https://fragment.com/gift/toybear-42129',
    'https://fragment.com/gift/toybear-36406',
    'https://fragment.com/gift/toybear-25762',
    'https://fragment.com/gift/toybear-32844',
    'https://fragment.com/gift/toybear-8634',
    'https://fragment.com/gift/toybear-8362',
    'https://fragment.com/gift/toybear-7639',
    'https://fragment.com/gift/toybear-53939',
    'https://fragment.com/gift/toybear-38787',
    'https://fragment.com/gift/toybear-23475',
    'https://fragment.com/gift/toybear-16535',
    'https://fragment.com/gift/toybear-16512',
    'https://fragment.com/gift/toybear-13628',
    'https://fragment.com/gift/toybear-12595',
    'https://fragment.com/gift/toybear-12434',
    'https://fragment.com/gift/snakebox-26400',
    'https://fragment.com/gift/snakebox-214',
    'https://fragment.com/gift/snakebox-1384',
    'https://fragment.com/gift/snakebox-12366',
    'https://fragment.com/gift/snakebox-10250',
    'https://fragment.com/gift/snakebox-6698',
    'https://fragment.com/gift/snakebox-998',
    'https://fragment.com/gift/snakebox-9558',
    'https://fragment.com/gift/snakebox-9051',
    'https://fragment.com/gift/snakebox-87112',
    'https://fragment.com/gift/snakebox-7587',
    'https://fragment.com/gift/snakebox-7535',
    'https://fragment.com/gift/snakebox-6305',
    'https://fragment.com/gift/snakebox-36033',
    'https://fragment.com/gift/snakebox-32375',
    'https://fragment.com/gift/homemadecake-4029',
    'https://fragment.com/gift/homemadecake-3824',
    'https://fragment.com/gift/homemadecake-3754',
    'https://fragment.com/gift/homemadecake-148471',
    'https://fragment.com/gift/homemadecake-129490',
    'https://fragment.com/gift/homemadecake-102427',
    'https://fragment.com/gift/homemadecake-79315',
    'https://fragment.com/gift/homemadecake-61337',
    'https://fragment.com/gift/homemadecake-61149',
    'https://fragment.com/gift/homemadecake-21311',
    'https://fragment.com/gift/homemadecake-162075',
    'https://fragment.com/gift/homemadecake-161359',
    'https://fragment.com/gift/homemadecake-19164',
    'https://fragment.com/gift/homemadecake-160954',
    'https://fragment.com/gift/homemadecake-103525',
    'https://fragment.com/gift/lolpop-142098',
    'https://fragment.com/gift/lolpop-141084',
    'https://fragment.com/gift/lolpop-127822',
    'https://fragment.com/gift/lolpop-358213',
    'https://fragment.com/gift/lolpop-203719',
    'https://fragment.com/gift/lolpop-202607',
    'https://fragment.com/gift/lolpop-82222',
    'https://fragment.com/gift/lolpop-284305',
    'https://fragment.com/gift/lolpop-253678',
    'https://fragment.com/gift/lolpop-222316',
    'https://fragment.com/gift/lolpop-136585',
    'https://fragment.com/gift/lolpop-192566',
    'https://fragment.com/gift/lolpop-289665',
    'https://fragment.com/gift/lolpop-10309',
    'https://fragment.com/gift/lolpop-50831',
    'https://fragment.com/gift/electricskull-5545',
    'https://fragment.com/gift/electricskull-5174',
    'https://fragment.com/gift/electricskull-3621',
    'https://fragment.com/gift/electricskull-8587',
    'https://fragment.com/gift/electricskull-5069',
    'https://fragment.com/gift/electricskull-2887',
    'https://fragment.com/gift/electricskull-8574',
    'https://fragment.com/gift/electricskull-6008',
    'https://fragment.com/gift/electricskull-4401',
    'https://fragment.com/gift/electricskull-4044',
    'https://fragment.com/gift/electricskull-278',
    'https://fragment.com/gift/electricskull-3726',
    'https://fragment.com/gift/electricskull-8589',
    'https://fragment.com/gift/electricskull-6665',
    'https://fragment.com/gift/electricskull-6191',
    'https://fragment.com/gift/hangingstar-29188',
    'https://fragment.com/gift/hangingstar-27911',
    'https://fragment.com/gift/hangingstar-2790',
    'https://fragment.com/gift/hangingstar-22500',
    'https://fragment.com/gift/hangingstar-20403',
    'https://fragment.com/gift/hangingstar-18465',
    'https://fragment.com/gift/hangingstar-17240',
    'https://fragment.com/gift/hangingstar-15229',
    'https://fragment.com/gift/hangingstar-10913',
    'https://fragment.com/gift/hangingstar-7104',
    'https://fragment.com/gift/hangingstar-1595',
    'https://fragment.com/gift/hangingstar-15476',
    'https://fragment.com/gift/hangingstar-10054',
    'https://fragment.com/gift/hangingstar-23281',
    'https://fragment.com/gift/hangingstar-12250',
    'https://fragment.com/gift/crystalball-4096',
    'https://fragment.com/gift/crystalball-228',
    'https://fragment.com/gift/crystalball-19811',
    'https://fragment.com/gift/crystalball-1784',
    'https://fragment.com/gift/crystalball-11224',
    'https://fragment.com/gift/crystalball-1033',
    'https://fragment.com/gift/crystalball-23106',
    'https://fragment.com/gift/crystalball-20783',
    'https://fragment.com/gift/crystalball-15625',
    'https://fragment.com/gift/crystalball-4950',
    'https://fragment.com/gift/crystalball-731',
    'https://fragment.com/gift/crystalball-7104',
    'https://fragment.com/gift/crystalball-653',
    'https://fragment.com/gift/crystalball-300',
    'https://fragment.com/gift/crystalball-19818',
    'https://fragment.com/gift/lootbag-10101',
    'https://fragment.com/gift/lootbag-10092',
    'https://fragment.com/gift/lootbag-8507',
    'https://fragment.com/gift/lootbag-274',
    'https://fragment.com/gift/lootbag-4897',
    'https://fragment.com/gift/lootbag-8060',
    'https://fragment.com/gift/lootbag-9964',
    'https://fragment.com/gift/lootbag-7515',
    'https://fragment.com/gift/lootbag-8689',
    'https://fragment.com/gift/lootbag-13851',
    'https://fragment.com/gift/lootbag-12282',
    'https://fragment.com/gift/lootbag-11760',
    'https://fragment.com/gift/lootbag-9814',
    'https://fragment.com/gift/lootbag-5008',
    'https://fragment.com/gift/lootbag-4805',
    'https://fragment.com/gift/hexpot-15175',
    'https://fragment.com/gift/hexpot-15893',
    'https://fragment.com/gift/hexpot-15729',
    'https://fragment.com/gift/hexpot-7558',
    'https://fragment.com/gift/hexpot-44322',
    'https://fragment.com/gift/hexpot-4000',
    'https://fragment.com/gift/hexpot-3704',
    'https://fragment.com/gift/hexpot-35856',
    'https://fragment.com/gift/hexpot-31794',
    'https://fragment.com/gift/hexpot-28794',
    'https://fragment.com/gift/hexpot-26617',
    'https://fragment.com/gift/hexpot-25644',
    'https://fragment.com/gift/hexpot-24955',
    'https://fragment.com/gift/hexpot-24890',
    'https://fragment.com/gift/hexpot-2255',
    'https://fragment.com/gift/freshsocks-32108',
    'https://fragment.com/gift/freshsocks-118834',
    'https://fragment.com/gift/freshsocks-89163',
    'https://fragment.com/gift/freshsocks-87110',
    'https://fragment.com/gift/freshsocks-438',
    'https://fragment.com/gift/freshsocks-13123',
    'https://fragment.com/gift/freshsocks-63890',
    'https://fragment.com/gift/freshsocks-19780',
    'https://fragment.com/gift/freshsocks-100353',
    'https://fragment.com/gift/freshsocks-92513',
    'https://fragment.com/gift/freshsocks-5109',
    'https://fragment.com/gift/freshsocks-35545',
    'https://fragment.com/gift/freshsocks-123108',
    'https://fragment.com/gift/freshsocks-122150',
    'https://fragment.com/gift/freshsocks-105547',
    'https://fragment.com/gift/swisswatch-1399',
    'https://fragment.com/gift/swisswatch-5005',
    'https://fragment.com/gift/swisswatch-17196',
    'https://fragment.com/gift/swisswatch-13275',
    'https://fragment.com/gift/swisswatch-21316',
    'https://fragment.com/gift/swisswatch-4204',
    'https://fragment.com/gift/swisswatch-23123',
    'https://fragment.com/gift/swisswatch-15553',
    'https://fragment.com/gift/swisswatch-21468',
    'https://fragment.com/gift/swisswatch-20974',
    'https://fragment.com/gift/swisswatch-2731',
    'https://fragment.com/gift/swisswatch-19108',
    'https://fragment.com/gift/swisswatch-17510',
    'https://fragment.com/gift/swisswatch-19195',
    'https://fragment.com/gift/swisswatch-1360',
    'https://fragment.com/gift/whipcupcake-86501',
    'https://fragment.com/gift/whipcupcake-56163',
    'https://fragment.com/gift/whipcupcake-28326',
    'https://fragment.com/gift/whipcupcake-25761',
    'https://fragment.com/gift/whipcupcake-142369',
    'https://fragment.com/gift/whipcupcake-133962',
    'https://fragment.com/gift/whipcupcake-72179',
    'https://fragment.com/gift/whipcupcake-7770',
    'https://fragment.com/gift/whipcupcake-30549',
    'https://fragment.com/gift/whipcupcake-174007',
    'https://fragment.com/gift/whipcupcake-9853',
    'https://fragment.com/gift/whipcupcake-9141',
    'https://fragment.com/gift/whipcupcake-6297',
    'https://fragment.com/gift/whipcupcake-40495',
    'https://fragment.com/gift/whipcupcake-31077',
    'https://fragment.com/gift/voodoodoll-4839',
    'https://fragment.com/gift/voodoodoll-15554',
    'https://fragment.com/gift/voodoodoll-15103',
    'https://fragment.com/gift/voodoodoll-11026',
    'https://fragment.com/gift/voodoodoll-10831',
    'https://fragment.com/gift/voodoodoll-7717',
    'https://fragment.com/gift/voodoodoll-21026',
    'https://fragment.com/gift/voodoodoll-6033',
    'https://fragment.com/gift/voodoodoll-3489',
    'https://fragment.com/gift/voodoodoll-23379',
    'https://fragment.com/gift/voodoodoll-22222',
    'https://fragment.com/gift/voodoodoll-20285',
    'https://fragment.com/gift/voodoodoll-10854',
    'https://fragment.com/gift/voodoodoll-1327',
    'https://fragment.com/gift/voodoodoll-22916',
    'https://fragment.com/gift/jinglebells-5624',
    'https://fragment.com/gift/jinglebells-54957',
    'https://fragment.com/gift/jinglebells-4533',
    'https://fragment.com/gift/jinglebells-43175',
    'https://fragment.com/gift/jinglebells-42484',
    'https://fragment.com/gift/jinglebells-3983',
    'https://fragment.com/gift/jinglebells-36098',
    'https://fragment.com/gift/jinglebells-34542',
    'https://fragment.com/gift/jinglebells-3258',
    'https://fragment.com/gift/jinglebells-3082',
    'https://fragment.com/gift/jinglebells-28696',
    'https://fragment.com/gift/jinglebells-27906',
    'https://fragment.com/gift/jinglebells-22670',
    'https://fragment.com/gift/jinglebells-190',
    'https://fragment.com/gift/jinglebells-10622',
    'https://fragment.com/gift/magicpotion-3318',
    'https://fragment.com/gift/magicpotion-3798',
    'https://fragment.com/gift/magicpotion-1352',
    'https://fragment.com/gift/magicpotion-4752',
    'https://fragment.com/gift/magicpotion-3304',
    'https://fragment.com/gift/magicpotion-3289',
    'https://fragment.com/gift/magicpotion-4390',
    'https://fragment.com/gift/magicpotion-203',
    'https://fragment.com/gift/magicpotion-1574',
    'https://fragment.com/gift/magicpotion-3233',
    'https://fragment.com/gift/magicpotion-3636',
    'https://fragment.com/gift/magicpotion-816',
    'https://fragment.com/gift/magicpotion-808',
    'https://fragment.com/gift/magicpotion-3957',
    'https://fragment.com/gift/magicpotion-3496',
    'https://fragment.com/gift/deskcalendar-33051',
    'https://fragment.com/gift/deskcalendar-31805',
    'https://fragment.com/gift/deskcalendar-310554',
    'https://fragment.com/gift/deskcalendar-309095',
    'https://fragment.com/gift/deskcalendar-202469',
    'https://fragment.com/gift/deskcalendar-97873',
    'https://fragment.com/gift/deskcalendar-261624',
    'https://fragment.com/gift/deskcalendar-98112',
    'https://fragment.com/gift/deskcalendar-47545',
    'https://fragment.com/gift/deskcalendar-266257',
    'https://fragment.com/gift/deskcalendar-12329',
    'https://fragment.com/gift/deskcalendar-38476',
    'https://fragment.com/gift/deskcalendar-312602',
    'https://fragment.com/gift/deskcalendar-284772',
    'https://fragment.com/gift/deskcalendar-267446',
    'https://fragment.com/gift/jollychimp-35851',
    'https://fragment.com/gift/jollychimp-27256',
    'https://fragment.com/gift/jollychimp-19969',
    'https://fragment.com/gift/jollychimp-17925',
    'https://fragment.com/gift/jollychimp-13993',
    'https://fragment.com/gift/jollychimp-51910',
    'https://fragment.com/gift/jollychimp-51150',
    'https://fragment.com/gift/jollychimp-35938',
    'https://fragment.com/gift/jollychimp-20360',
    'https://fragment.com/gift/jollychimp-15700',
    'https://fragment.com/gift/jollychimp-66159',
    'https://fragment.com/gift/jollychimp-2942',
    'https://fragment.com/gift/jollychimp-17136',
    'https://fragment.com/gift/jollychimp-7819',
    'https://fragment.com/gift/jollychimp-49191',
    'https://fragment.com/gift/tamagadget-52081',
    'https://fragment.com/gift/tamagadget-520',
    'https://fragment.com/gift/tamagadget-28851',
    'https://fragment.com/gift/tamagadget-15248',
    'https://fragment.com/gift/tamagadget-6302',
    'https://fragment.com/gift/tamagadget-42268',
    'https://fragment.com/gift/tamagadget-49068',
    'https://fragment.com/gift/tamagadget-50492',
    'https://fragment.com/gift/tamagadget-44261',
    'https://fragment.com/gift/tamagadget-12053',
    'https://fragment.com/gift/tamagadget-9455',
    'https://fragment.com/gift/tamagadget-56438',
    'https://fragment.com/gift/tamagadget-40776',
    'https://fragment.com/gift/tamagadget-40000',
    'https://fragment.com/gift/tamagadget-23356',
    'https://fragment.com/gift/bunnymuffin-13900',
    'https://fragment.com/gift/bunnymuffin-12614',
    'https://fragment.com/gift/bunnymuffin-12486',
    'https://fragment.com/gift/bunnymuffin-9790',
    'https://fragment.com/gift/bunnymuffin-3836',
    'https://fragment.com/gift/bunnymuffin-26293',
    'https://fragment.com/gift/bunnymuffin-11274',
    'https://fragment.com/gift/bunnymuffin-5462',
    'https://fragment.com/gift/bunnymuffin-26296',
    'https://fragment.com/gift/bunnymuffin-14526',
    'https://fragment.com/gift/bunnymuffin-35426',
    'https://fragment.com/gift/bunnymuffin-33887',
    'https://fragment.com/gift/bunnymuffin-17136',
    'https://fragment.com/gift/bunnymuffin-11783',
    'https://fragment.com/gift/bunnymuffin-10355',
    'https://fragment.com/gift/snoopdogg-1520',
    'https://fragment.com/gift/snoopdogg-73507',
    'https://fragment.com/gift/snoopdogg-519946',
    'https://fragment.com/gift/snoopdogg-479261',
    'https://fragment.com/gift/snoopdogg-3333',
    'https://fragment.com/gift/snoopdogg-112887',
    'https://fragment.com/gift/snoopdogg-377865',
    'https://fragment.com/gift/snoopdogg-536405',
    'https://fragment.com/gift/snoopdogg-513333',
    'https://fragment.com/gift/snoopdogg-512666',
    'https://fragment.com/gift/snoopdogg-479088',
    'https://fragment.com/gift/snoopdogg-379469',
    'https://fragment.com/gift/snoopdogg-31082',
    'https://fragment.com/gift/snoopdogg-293681',
    'https://fragment.com/gift/snoopdogg-282993',
    'https://fragment.com/gift/spicedwine-9111',
    'https://fragment.com/gift/spicedwine-7427',
    'https://fragment.com/gift/spicedwine-5447',
    'https://fragment.com/gift/spicedwine-50020',
    'https://fragment.com/gift/spicedwine-500',
    'https://fragment.com/gift/spicedwine-26525',
    'https://fragment.com/gift/spicedwine-23276',
    'https://fragment.com/gift/spicedwine-18104',
    'https://fragment.com/gift/spicedwine-13274',
    'https://fragment.com/gift/spicedwine-10255',
    'https://fragment.com/gift/spicedwine-41185',
    'https://fragment.com/gift/spicedwine-34550',
    'https://fragment.com/gift/spicedwine-18933',
    'https://fragment.com/gift/spicedwine-42726',
    'https://fragment.com/gift/spicedwine-41',
    'https://fragment.com/gift/inputkey-59675',
    'https://fragment.com/gift/inputkey-50556',
    'https://fragment.com/gift/inputkey-29084',
    'https://fragment.com/gift/inputkey-20885',
    'https://fragment.com/gift/inputkey-48979',
    'https://fragment.com/gift/inputkey-27623',
    'https://fragment.com/gift/inputkey-104838',
    'https://fragment.com/gift/inputkey-10206',
    'https://fragment.com/gift/inputkey-17063',
    'https://fragment.com/gift/inputkey-67069',
    'https://fragment.com/gift/inputkey-60030',
    'https://fragment.com/gift/inputkey-52484',
    'https://fragment.com/gift/inputkey-34439',
    'https://fragment.com/gift/inputkey-8694',
    'https://fragment.com/gift/inputkey-81860',
    'https://fragment.com/gift/hypnolollipop-22224',
    'https://fragment.com/gift/hypnolollipop-2012',
    'https://fragment.com/gift/hypnolollipop-42066',
    'https://fragment.com/gift/hypnolollipop-31722',
    'https://fragment.com/gift/hypnolollipop-25114',
    'https://fragment.com/gift/hypnolollipop-520',
    'https://fragment.com/gift/hypnolollipop-11989',
    'https://fragment.com/gift/hypnolollipop-6700',
    'https://fragment.com/gift/hypnolollipop-48720',
    'https://fragment.com/gift/hypnolollipop-2737',
    'https://fragment.com/gift/hypnolollipop-23605',
    'https://fragment.com/gift/hypnolollipop-22943',
    'https://fragment.com/gift/hypnolollipop-18276',
    'https://fragment.com/gift/hypnolollipop-14430',
    'https://fragment.com/gift/hypnolollipop-1567',
    'https://fragment.com/gift/snowmittens-15418',
    'https://fragment.com/gift/snowmittens-12070',
    'https://fragment.com/gift/snowmittens-10334',
    'https://fragment.com/gift/snowmittens-10136',
    'https://fragment.com/gift/snowmittens-9916',
    'https://fragment.com/gift/snowmittens-9789',
    'https://fragment.com/gift/snowmittens-6227',
    'https://fragment.com/gift/snowmittens-3262',
    'https://fragment.com/gift/snowmittens-12592',
    'https://fragment.com/gift/snowmittens-1161',
    'https://fragment.com/gift/snowmittens-7771',
    'https://fragment.com/gift/snowmittens-4743',
    'https://fragment.com/gift/snowmittens-465',
    'https://fragment.com/gift/snowmittens-3773',
    'https://fragment.com/gift/snowmittens-32538',
    'https://fragment.com/gift/snoopcigar-12721',
    'https://fragment.com/gift/snoopcigar-108647',
    'https://fragment.com/gift/snoopcigar-103014',
    'https://fragment.com/gift/snoopcigar-37295',
    'https://fragment.com/gift/snoopcigar-14079',
    'https://fragment.com/gift/snoopcigar-6015',
    'https://fragment.com/gift/snoopcigar-58490',
    'https://fragment.com/gift/snoopcigar-15489',
    'https://fragment.com/gift/snoopcigar-103810',
    'https://fragment.com/gift/snoopcigar-57301',
    'https://fragment.com/gift/snoopcigar-36235',
    'https://fragment.com/gift/snoopcigar-34103',
    'https://fragment.com/gift/snoopcigar-108640',
    'https://fragment.com/gift/snoopcigar-69132',
    'https://fragment.com/gift/snoopcigar-8643',
    'https://fragment.com/gift/lowrider-17124',
    'https://fragment.com/gift/lowrider-15952',
    'https://fragment.com/gift/lowrider-1557',
    'https://fragment.com/gift/lowrider-14950',
    'https://fragment.com/gift/lowrider-11309',
    'https://fragment.com/gift/lowrider-10514',
    'https://fragment.com/gift/lowrider-10878',
    'https://fragment.com/gift/lowrider-4247',
    'https://fragment.com/gift/lowrider-9861',
    'https://fragment.com/gift/lowrider-22079',
    'https://fragment.com/gift/lowrider-20716',
    'https://fragment.com/gift/lowrider-13468',
    'https://fragment.com/gift/lowrider-5802',
    'https://fragment.com/gift/lowrider-5365',
    'https://fragment.com/gift/lowrider-3999',
    'https://fragment.com/gift/xmasstocking-1282',
    'https://fragment.com/gift/xmasstocking-120987',
    'https://fragment.com/gift/xmasstocking-100541',
    'https://fragment.com/gift/xmasstocking-75693',
    'https://fragment.com/gift/xmasstocking-53620',
    'https://fragment.com/gift/xmasstocking-51738',
    'https://fragment.com/gift/xmasstocking-44010',
    'https://fragment.com/gift/xmasstocking-37056',
    'https://fragment.com/gift/xmasstocking-33312',
    'https://fragment.com/gift/xmasstocking-126428',
    'https://fragment.com/gift/xmasstocking-125467',
    'https://fragment.com/gift/xmasstocking-118178',
    'https://fragment.com/gift/xmasstocking-95982',
    'https://fragment.com/gift/xmasstocking-91026',
    'https://fragment.com/gift/xmasstocking-57571',
    'https://fragment.com/gift/gingercookie-68032',
    'https://fragment.com/gift/gingercookie-48955',
    'https://fragment.com/gift/gingercookie-44374',
    'https://fragment.com/gift/gingercookie-38700',
    'https://fragment.com/gift/gingercookie-38092',
    'https://fragment.com/gift/gingercookie-20363',
    'https://fragment.com/gift/gingercookie-12533',
    'https://fragment.com/gift/gingercookie-101074',
    'https://fragment.com/gift/gingercookie-65276',
    'https://fragment.com/gift/gingercookie-100102',
    'https://fragment.com/gift/gingercookie-95037',
    'https://fragment.com/gift/gingercookie-7935',
    'https://fragment.com/gift/gingercookie-2673',
    'https://fragment.com/gift/gingercookie-222',
    'https://fragment.com/gift/gingercookie-59715',
    'https://fragment.com/gift/tophat-16547',
    'https://fragment.com/gift/tophat-15909',
    'https://fragment.com/gift/tophat-12934',
    'https://fragment.com/gift/tophat-11195',
    'https://fragment.com/gift/tophat-12440',
    'https://fragment.com/gift/tophat-11666',
    'https://fragment.com/gift/tophat-6400',
    'https://fragment.com/gift/tophat-6331',
    'https://fragment.com/gift/tophat-31367',
    'https://fragment.com/gift/tophat-18468',
    'https://fragment.com/gift/tophat-16762',
    'https://fragment.com/gift/tophat-8548',
    'https://fragment.com/gift/tophat-5029',
    'https://fragment.com/gift/tophat-25705',
    'https://fragment.com/gift/tophat-20373',
    'https://fragment.com/gift/vintagecigar-7755',
    'https://fragment.com/gift/vintagecigar-19641',
    'https://fragment.com/gift/vintagecigar-738',
    'https://fragment.com/gift/vintagecigar-1263',
    'https://fragment.com/gift/vintagecigar-14383',
    'https://fragment.com/gift/vintagecigar-13191',
    'https://fragment.com/gift/vintagecigar-13300',
    'https://fragment.com/gift/vintagecigar-28',
    'https://fragment.com/gift/vintagecigar-8388',
    'https://fragment.com/gift/vintagecigar-12899',
    'https://fragment.com/gift/vintagecigar-14606',
    'https://fragment.com/gift/vintagecigar-7087',
    'https://fragment.com/gift/vintagecigar-5902',
    'https://fragment.com/gift/vintagecigar-5827',
    'https://fragment.com/gift/vintagecigar-21276',
    'https://fragment.com/gift/skystilettos-22555',
    'https://fragment.com/gift/skystilettos-18499',
    'https://fragment.com/gift/skystilettos-17774',
    'https://fragment.com/gift/skystilettos-12750',
    'https://fragment.com/gift/skystilettos-12039',
    'https://fragment.com/gift/skystilettos-11306',
    'https://fragment.com/gift/skystilettos-10578',
    'https://fragment.com/gift/skystilettos-9820',
    'https://fragment.com/gift/skystilettos-43429',
    'https://fragment.com/gift/skystilettos-3509',
    'https://fragment.com/gift/skystilettos-30789',
    'https://fragment.com/gift/skystilettos-27946',
    'https://fragment.com/gift/skystilettos-27085',
    'https://fragment.com/gift/skystilettos-18401',
    'https://fragment.com/gift/skystilettos-12206',
    'https://fragment.com/gift/perfumebottle-283',
    'https://fragment.com/gift/perfumebottle-1754',
    'https://fragment.com/gift/perfumebottle-1343',
    'https://fragment.com/gift/perfumebottle-1294',
    'https://fragment.com/gift/perfumebottle-3947',
    'https://fragment.com/gift/perfumebottle-710',
    'https://fragment.com/gift/perfumebottle-3684',
    'https://fragment.com/gift/perfumebottle-777',
    'https://fragment.com/gift/perfumebottle-1576',
    'https://fragment.com/gift/perfumebottle-2295',
    'https://fragment.com/gift/perfumebottle-799',
    'https://fragment.com/gift/perfumebottle-1923',
    'https://fragment.com/gift/perfumebottle-4302',
    'https://fragment.com/gift/perfumebottle-2232',
    'https://fragment.com/gift/perfumebottle-929',
    'https://fragment.com/gift/holidaydrink-11951',
    'https://fragment.com/gift/holidaydrink-11796',
    'https://fragment.com/gift/holidaydrink-10103',
    'https://fragment.com/gift/holidaydrink-9901',
    'https://fragment.com/gift/holidaydrink-969',
    'https://fragment.com/gift/holidaydrink-9000',
    'https://fragment.com/gift/holidaydrink-764',
    'https://fragment.com/gift/holidaydrink-50772',
    'https://fragment.com/gift/holidaydrink-5075',
    'https://fragment.com/gift/holidaydrink-3883',
    'https://fragment.com/gift/holidaydrink-37125',
    'https://fragment.com/gift/holidaydrink-11923',
    'https://fragment.com/gift/holidaydrink-98',
    'https://fragment.com/gift/holidaydrink-8530',
    'https://fragment.com/gift/holidaydrink-8087',
    'https://fragment.com/gift/moonpendant-90301',
    'https://fragment.com/gift/moonpendant-858',
    'https://fragment.com/gift/moonpendant-84868',
    'https://fragment.com/gift/moonpendant-6582',
    'https://fragment.com/gift/moonpendant-4643',
    'https://fragment.com/gift/moonpendant-84766',
    'https://fragment.com/gift/moonpendant-82166',
    'https://fragment.com/gift/moonpendant-75510',
    'https://fragment.com/gift/moonpendant-64095',
    'https://fragment.com/gift/moonpendant-40065',
    'https://fragment.com/gift/moonpendant-39091',
    'https://fragment.com/gift/moonpendant-36677',
    'https://fragment.com/gift/moonpendant-20016',
    'https://fragment.com/gift/moonpendant-54173',
    'https://fragment.com/gift/moonpendant-56021',
    'https://fragment.com/gift/sharptongue-1476',
    'https://fragment.com/gift/sharptongue-3441',
    'https://fragment.com/gift/sharptongue-3528',
    'https://fragment.com/gift/sharptongue-2097',
    'https://fragment.com/gift/sharptongue-924',
    'https://fragment.com/gift/sharptongue-5948',
    'https://fragment.com/gift/sharptongue-7547',
    'https://fragment.com/gift/sharptongue-2970',
    'https://fragment.com/gift/sharptongue-1684',
    'https://fragment.com/gift/sharptongue-1101',
    'https://fragment.com/gift/sharptongue-5814',
    'https://fragment.com/gift/sharptongue-2149',
    'https://fragment.com/gift/sharptongue-882',
    'https://fragment.com/gift/sharptongue-903',
    'https://fragment.com/gift/sharptongue-6888',
    'https://fragment.com/gift/jesterhat-6021',
    'https://fragment.com/gift/jesterhat-51627',
    'https://fragment.com/gift/jesterhat-33796',
    'https://fragment.com/gift/jesterhat-22503',
    'https://fragment.com/gift/jesterhat-70658',
    'https://fragment.com/gift/jesterhat-23790',
    'https://fragment.com/gift/jesterhat-6818',
    'https://fragment.com/gift/jesterhat-56979',
    'https://fragment.com/gift/jesterhat-77436',
    'https://fragment.com/gift/jesterhat-35742',
    'https://fragment.com/gift/jesterhat-255',
    'https://fragment.com/gift/jesterhat-14795',
    'https://fragment.com/gift/jesterhat-1099',
    'https://fragment.com/gift/jesterhat-35128',
    'https://fragment.com/gift/jesterhat-2343',
    'https://fragment.com/gift/spyagaric-38302',
    'https://fragment.com/gift/spyagaric-38298',
    'https://fragment.com/gift/spyagaric-38190',
    'https://fragment.com/gift/spyagaric-30735',
    'https://fragment.com/gift/spyagaric-16842',
    'https://fragment.com/gift/spyagaric-10799',
    'https://fragment.com/gift/spyagaric-48398',
    'https://fragment.com/gift/spyagaric-38453',
    'https://fragment.com/gift/spyagaric-2078',
    'https://fragment.com/gift/spyagaric-27804',
    'https://fragment.com/gift/spyagaric-68445',
    'https://fragment.com/gift/spyagaric-58757',
    'https://fragment.com/gift/spyagaric-58529',
    'https://fragment.com/gift/spyagaric-73886',
    'https://fragment.com/gift/spyagaric-71709',
    'https://fragment.com/gift/iongem-1762',
    'https://fragment.com/gift/iongem-3261',
    'https://fragment.com/gift/iongem-1699',
    'https://fragment.com/gift/iongem-640',
    'https://fragment.com/gift/iongem-3522',
    'https://fragment.com/gift/iongem-746',
    'https://fragment.com/gift/iongem-2521',
    'https://fragment.com/gift/iongem-2155',
    'https://fragment.com/gift/iongem-3662',
    'https://fragment.com/gift/iongem-2420',
    'https://fragment.com/gift/iongem-636',
    'https://fragment.com/gift/iongem-2857',
    'https://fragment.com/gift/iongem-3571',
    'https://fragment.com/gift/iongem-4191',
    'https://fragment.com/gift/iongem-3536',
    'https://fragment.com/gift/cloverpin-99997',
    'https://fragment.com/gift/cloverpin-84542',
    'https://fragment.com/gift/cloverpin-71285',
    'https://fragment.com/gift/cloverpin-69602',
    'https://fragment.com/gift/cloverpin-68451',
    'https://fragment.com/gift/cloverpin-67708',
    'https://fragment.com/gift/cloverpin-62822',
    'https://fragment.com/gift/cloverpin-59541',
    'https://fragment.com/gift/cloverpin-51671',
    'https://fragment.com/gift/cloverpin-45040',
    'https://fragment.com/gift/cloverpin-43995',
    'https://fragment.com/gift/cloverpin-3290',
    'https://fragment.com/gift/cloverpin-212188',
    'https://fragment.com/gift/cloverpin-184441',
    'https://fragment.com/gift/cloverpin-132379',
    'https://fragment.com/gift/valentinebox-665',
    'https://fragment.com/gift/valentinebox-6508',
    'https://fragment.com/gift/valentinebox-613',
    'https://fragment.com/gift/valentinebox-12796',
    'https://fragment.com/gift/valentinebox-10561',
    'https://fragment.com/gift/valentinebox-9096',
    'https://fragment.com/gift/valentinebox-8936',
    'https://fragment.com/gift/valentinebox-7114',
    'https://fragment.com/gift/valentinebox-6055',
    'https://fragment.com/gift/valentinebox-570',
    'https://fragment.com/gift/valentinebox-22229',
    'https://fragment.com/gift/valentinebox-17684',
    'https://fragment.com/gift/valentinebox-9003',
    'https://fragment.com/gift/valentinebox-8643',
    'https://fragment.com/gift/valentinebox-7117',
    'https://fragment.com/gift/eternalcandle-28965',
    'https://fragment.com/gift/eternalcandle-21424',
    'https://fragment.com/gift/eternalcandle-15985',
    'https://fragment.com/gift/eternalcandle-38',
    'https://fragment.com/gift/eternalcandle-22227',
    'https://fragment.com/gift/eternalcandle-9621',
    'https://fragment.com/gift/eternalcandle-8262',
    'https://fragment.com/gift/eternalcandle-7852',
    'https://fragment.com/gift/eternalcandle-578',
    'https://fragment.com/gift/eternalcandle-5084',
    'https://fragment.com/gift/eternalcandle-462',
    'https://fragment.com/gift/eternalcandle-334',
    'https://fragment.com/gift/eternalcandle-28046',
    'https://fragment.com/gift/eternalcandle-25520',
    'https://fragment.com/gift/eternalcandle-21689',
    'https://fragment.com/gift/lightsword-10514',
    'https://fragment.com/gift/lightsword-19868',
    'https://fragment.com/gift/lightsword-53819',
    'https://fragment.com/gift/lightsword-37386',
    'https://fragment.com/gift/lightsword-20970',
    'https://fragment.com/gift/lightsword-5386',
    'https://fragment.com/gift/lightsword-49232',
    'https://fragment.com/gift/lightsword-42754',
    'https://fragment.com/gift/lightsword-4112',
    'https://fragment.com/gift/lightsword-19871',
    'https://fragment.com/gift/lightsword-110330',
    'https://fragment.com/gift/lightsword-67774',
    'https://fragment.com/gift/lightsword-4230',
    'https://fragment.com/gift/lightsword-87617',
    'https://fragment.com/gift/lightsword-43106',
    'https://fragment.com/gift/stellarrocket-25330',
    'https://fragment.com/gift/stellarrocket-124937',
    'https://fragment.com/gift/stellarrocket-30812',
    'https://fragment.com/gift/stellarrocket-33116',
    'https://fragment.com/gift/stellarrocket-77753',
    'https://fragment.com/gift/stellarrocket-18845',
    'https://fragment.com/gift/stellarrocket-97289',
    'https://fragment.com/gift/stellarrocket-82841',
    'https://fragment.com/gift/stellarrocket-45688',
    'https://fragment.com/gift/stellarrocket-32408',
    'https://fragment.com/gift/stellarrocket-78727',
    'https://fragment.com/gift/stellarrocket-400',
    'https://fragment.com/gift/stellarrocket-62690',
    'https://fragment.com/gift/stellarrocket-9527',
    'https://fragment.com/gift/stellarrocket-8202',
    'https://fragment.com/gift/springbasket-45695',
    'https://fragment.com/gift/springbasket-40580',
    'https://fragment.com/gift/springbasket-33152',
    'https://fragment.com/gift/springbasket-31703',
    'https://fragment.com/gift/springbasket-26171',
    'https://fragment.com/gift/springbasket-25584',
    'https://fragment.com/gift/springbasket-131312',
    'https://fragment.com/gift/springbasket-11916',
    'https://fragment.com/gift/springbasket-10988',
    'https://fragment.com/gift/springbasket-102524',
    'https://fragment.com/gift/springbasket-92021',
    'https://fragment.com/gift/springbasket-50458',
    'https://fragment.com/gift/springbasket-10007',
    'https://fragment.com/gift/springbasket-40131',
    'https://fragment.com/gift/springbasket-36754',
    'https://fragment.com/gift/lovepotion-17602',
    'https://fragment.com/gift/lovepotion-1733',
    'https://fragment.com/gift/lovepotion-16826',
    'https://fragment.com/gift/lovepotion-16064',
    'https://fragment.com/gift/lovepotion-13775',
    'https://fragment.com/gift/lovepotion-13436',
    'https://fragment.com/gift/lovepotion-13406',
    'https://fragment.com/gift/lovepotion-13336',
    'https://fragment.com/gift/lovepotion-12000',
    'https://fragment.com/gift/lovepotion-19712',
    'https://fragment.com/gift/lovepotion-12013',
    'https://fragment.com/gift/lovepotion-9779',
    'https://fragment.com/gift/lovepotion-6178',
    'https://fragment.com/gift/lovepotion-22940',
    'https://fragment.com/gift/lovepotion-19895',
    'https://fragment.com/gift/cupidcharm-17545',
    'https://fragment.com/gift/cupidcharm-16695',
    'https://fragment.com/gift/cupidcharm-16314',
    'https://fragment.com/gift/cupidcharm-15022',
    'https://fragment.com/gift/cupidcharm-1129',
    'https://fragment.com/gift/cupidcharm-26051',
    'https://fragment.com/gift/cupidcharm-27448',
    'https://fragment.com/gift/cupidcharm-7423',
    'https://fragment.com/gift/cupidcharm-6579',
    'https://fragment.com/gift/cupidcharm-6478',
    'https://fragment.com/gift/cupidcharm-22393',
    'https://fragment.com/gift/cupidcharm-13677',
    'https://fragment.com/gift/cupidcharm-26380',
    'https://fragment.com/gift/cupidcharm-217',
    'https://fragment.com/gift/cupidcharm-9176',
    'https://fragment.com/gift/happybrownie-101111',
    'https://fragment.com/gift/happybrownie-100517',
    'https://fragment.com/gift/happybrownie-103287',
    'https://fragment.com/gift/happybrownie-100046',
    'https://fragment.com/gift/happybrownie-91998',
    'https://fragment.com/gift/happybrownie-76733',
    'https://fragment.com/gift/happybrownie-59727',
    'https://fragment.com/gift/happybrownie-45658',
    'https://fragment.com/gift/happybrownie-324',
    'https://fragment.com/gift/happybrownie-23526',
    'https://fragment.com/gift/happybrownie-180832',
    'https://fragment.com/gift/happybrownie-177177',
    'https://fragment.com/gift/happybrownie-145176',
    'https://fragment.com/gift/happybrownie-143977',
    'https://fragment.com/gift/happybrownie-129101',
    'https://fragment.com/gift/sakuraflower-17713',
    'https://fragment.com/gift/sakuraflower-16355',
    'https://fragment.com/gift/sakuraflower-13287',
    'https://fragment.com/gift/sakuraflower-10837',
    'https://fragment.com/gift/sakuraflower-10811',
    'https://fragment.com/gift/sakuraflower-10445',
    'https://fragment.com/gift/sakuraflower-613',
    'https://fragment.com/gift/sakuraflower-14163',
    'https://fragment.com/gift/sakuraflower-28130',
    'https://fragment.com/gift/sakuraflower-14950',
    'https://fragment.com/gift/sakuraflower-5888',
    'https://fragment.com/gift/sakuraflower-29292',
    'https://fragment.com/gift/sakuraflower-17109',
    'https://fragment.com/gift/sakuraflower-9359',
    'https://fragment.com/gift/sakuraflower-9136',
    'https://fragment.com/gift/partysparkler-7455',
    'https://fragment.com/gift/partysparkler-66829',
    'https://fragment.com/gift/partysparkler-66593',
    'https://fragment.com/gift/partysparkler-49775',
    'https://fragment.com/gift/partysparkler-21709',
    'https://fragment.com/gift/partysparkler-14077',
    'https://fragment.com/gift/partysparkler-138372',
    'https://fragment.com/gift/partysparkler-138205',
    'https://fragment.com/gift/partysparkler-8763',
    'https://fragment.com/gift/partysparkler-62681',
    'https://fragment.com/gift/partysparkler-99229',
    'https://fragment.com/gift/partysparkler-9704',
    'https://fragment.com/gift/partysparkler-9615',
    'https://fragment.com/gift/partysparkler-9282',
    'https://fragment.com/gift/partysparkler-8881',
    'https://fragment.com/gift/genielamp-1355',
    'https://fragment.com/gift/genielamp-98',
    'https://fragment.com/gift/genielamp-746',
    'https://fragment.com/gift/genielamp-466',
    'https://fragment.com/gift/genielamp-451',
    'https://fragment.com/gift/genielamp-4',
    'https://fragment.com/gift/genielamp-338',
    'https://fragment.com/gift/genielamp-324',
    'https://fragment.com/gift/genielamp-278',
    'https://fragment.com/gift/genielamp-2637',
    'https://fragment.com/gift/genielamp-2618',
    'https://fragment.com/gift/genielamp-1929',
    'https://fragment.com/gift/genielamp-1796',
    'https://fragment.com/gift/genielamp-1524',
    'https://fragment.com/gift/genielamp-1435',
    'https://fragment.com/gift/lunarsnake-42521',
    'https://fragment.com/gift/lunarsnake-37989',
    'https://fragment.com/gift/lunarsnake-29394',
    'https://fragment.com/gift/lunarsnake-21856',
    'https://fragment.com/gift/lunarsnake-16999',
    'https://fragment.com/gift/lunarsnake-146521',
    'https://fragment.com/gift/lunarsnake-13687',
    'https://fragment.com/gift/lunarsnake-11195',
    'https://fragment.com/gift/lunarsnake-51217',
    'https://fragment.com/gift/lunarsnake-49433',
    'https://fragment.com/gift/lunarsnake-23457',
    'https://fragment.com/gift/lunarsnake-154382',
    'https://fragment.com/gift/lunarsnake-137776',
    'https://fragment.com/gift/lunarsnake-1057',
    'https://fragment.com/gift/lunarsnake-36125',
    'https://fragment.com/gift/instantramen-234383',
    'https://fragment.com/gift/instantramen-229450',
    'https://fragment.com/gift/instantramen-182992',
    'https://fragment.com/gift/instantramen-177302',
    'https://fragment.com/gift/instantramen-121478',
    'https://fragment.com/gift/instantramen-97448',
    'https://fragment.com/gift/instantramen-83527',
    'https://fragment.com/gift/instantramen-81016',
    'https://fragment.com/gift/instantramen-5626',
    'https://fragment.com/gift/instantramen-5547',
    'https://fragment.com/gift/instantramen-88158',
    'https://fragment.com/gift/instantramen-83291',
    'https://fragment.com/gift/instantramen-7238',
    'https://fragment.com/gift/instantramen-53788',
    'https://fragment.com/gift/instantramen-33341',
    'https://fragment.com/gift/recordplayer-24372',
    'https://fragment.com/gift/recordplayer-2086',
    'https://fragment.com/gift/recordplayer-20855',
    'https://fragment.com/gift/recordplayer-20554',
    'https://fragment.com/gift/recordplayer-20369',
    'https://fragment.com/gift/recordplayer-19923',
    'https://fragment.com/gift/recordplayer-19111',
    'https://fragment.com/gift/recordplayer-19071',
    'https://fragment.com/gift/recordplayer-18667',
    'https://fragment.com/gift/recordplayer-18575',
    'https://fragment.com/gift/recordplayer-17241',
    'https://fragment.com/gift/recordplayer-16628',
    'https://fragment.com/gift/recordplayer-14664',
    'https://fragment.com/gift/recordplayer-1112',
    'https://fragment.com/gift/recordplayer-9900',
    'https://fragment.com/gift/ionicdryer-16164',
    'https://fragment.com/gift/ionicdryer-15118',
    'https://fragment.com/gift/ionicdryer-1229',
    'https://fragment.com/gift/ionicdryer-11171',
    'https://fragment.com/gift/ionicdryer-11077',
    'https://fragment.com/gift/ionicdryer-2122',
    'https://fragment.com/gift/ionicdryer-17024',
    'https://fragment.com/gift/ionicdryer-12090',
    'https://fragment.com/gift/ionicdryer-1159',
    'https://fragment.com/gift/ionicdryer-9399',
    'https://fragment.com/gift/ionicdryer-8177',
    'https://fragment.com/gift/ionicdryer-7046',
    'https://fragment.com/gift/ionicdryer-6329',
    'https://fragment.com/gift/ionicdryer-471',
    'https://fragment.com/gift/ionicdryer-4453',
    'https://fragment.com/gift/sleighbell-559',
    'https://fragment.com/gift/sleighbell-4550',
    'https://fragment.com/gift/sleighbell-3334',
    'https://fragment.com/gift/sleighbell-3085',
    'https://fragment.com/gift/sleighbell-2747',
    'https://fragment.com/gift/sleighbell-1448',
    'https://fragment.com/gift/sleighbell-13979',
    'https://fragment.com/gift/sleighbell-1382',
    'https://fragment.com/gift/sleighbell-13579',
    'https://fragment.com/gift/sleighbell-12287',
    'https://fragment.com/gift/sleighbell-1228',
    'https://fragment.com/gift/sleighbell-12226',
    'https://fragment.com/gift/sleighbell-12096',
    'https://fragment.com/gift/sleighbell-11559',
    'https://fragment.com/gift/sleighbell-11200',
    'https://fragment.com/gift/moussecake-75829',
    'https://fragment.com/gift/moussecake-72426',
    'https://fragment.com/gift/moussecake-66605',
    'https://fragment.com/gift/moussecake-66516',
    'https://fragment.com/gift/moussecake-6417',
    'https://fragment.com/gift/moussecake-57813',
    'https://fragment.com/gift/moussecake-55533',
    'https://fragment.com/gift/moussecake-46148',
    'https://fragment.com/gift/moussecake-46085',
    'https://fragment.com/gift/moussecake-44950',
    'https://fragment.com/gift/moussecake-42574',
    'https://fragment.com/gift/moussecake-42525',
    'https://fragment.com/gift/moussecake-31882',
    'https://fragment.com/gift/moussecake-31454',
    'https://fragment.com/gift/moussecake-2613',
    'https://fragment.com/gift/icecream-10032',
    'https://fragment.com/gift/icecream-96052',
    'https://fragment.com/gift/icecream-439',
    'https://fragment.com/gift/icecream-203278',
    'https://fragment.com/gift/icecream-177631',
    'https://fragment.com/gift/icecream-147919',
    'https://fragment.com/gift/icecream-80803',
    'https://fragment.com/gift/icecream-45679',
    'https://fragment.com/gift/icecream-42835',
    'https://fragment.com/gift/icecream-23973',
    'https://fragment.com/gift/icecream-153',
    'https://fragment.com/gift/icecream-145411',
    'https://fragment.com/gift/icecream-219553',
    'https://fragment.com/gift/icecream-74901',
    'https://fragment.com/gift/icecream-189946',
    'https://fragment.com/gift/westsidesign-7828',
    'https://fragment.com/gift/westsidesign-6795',
    'https://fragment.com/gift/westsidesign-5039',
    'https://fragment.com/gift/westsidesign-4200',
    'https://fragment.com/gift/westsidesign-4068',
    'https://fragment.com/gift/westsidesign-3431',
    'https://fragment.com/gift/westsidesign-2757',
    'https://fragment.com/gift/westsidesign-1770',
    'https://fragment.com/gift/westsidesign-10922',
    'https://fragment.com/gift/westsidesign-7700',
    'https://fragment.com/gift/westsidesign-9850',
    'https://fragment.com/gift/westsidesign-1513',
    'https://fragment.com/gift/westsidesign-7670',
    'https://fragment.com/gift/westsidesign-4683',
    'https://fragment.com/gift/westsidesign-7878',
    'https://fragment.com/gift/cookieheart-112617',
    'https://fragment.com/gift/cookieheart-112044',
    'https://fragment.com/gift/cookieheart-107946',
    'https://fragment.com/gift/cookieheart-1059',
    'https://fragment.com/gift/cookieheart-101860',
    'https://fragment.com/gift/cookieheart-99151',
    'https://fragment.com/gift/cookieheart-30982',
    'https://fragment.com/gift/cookieheart-21692',
    'https://fragment.com/gift/cookieheart-124253',
    'https://fragment.com/gift/cookieheart-110055',
    'https://fragment.com/gift/cookieheart-112840',
    'https://fragment.com/gift/cookieheart-89552',
    'https://fragment.com/gift/cookieheart-8359',
    'https://fragment.com/gift/cookieheart-79138',
    'https://fragment.com/gift/cookieheart-77878',
    'https://fragment.com/gift/signetring-4939',
    'https://fragment.com/gift/signetring-4454',
    'https://fragment.com/gift/signetring-10138',
    'https://fragment.com/gift/signetring-5038',
    'https://fragment.com/gift/signetring-14207',
    'https://fragment.com/gift/signetring-3105',
    'https://fragment.com/gift/signetring-12338',
    'https://fragment.com/gift/signetring-13440',
    'https://fragment.com/gift/signetring-2297',
    'https://fragment.com/gift/signetring-2755',
    'https://fragment.com/gift/signetring-1506',
    'https://fragment.com/gift/signetring-9019',
    'https://fragment.com/gift/signetring-4661',
    'https://fragment.com/gift/signetring-4154',
    'https://fragment.com/gift/signetring-394',
    'https://fragment.com/gift/restlessjar-14209',
    'https://fragment.com/gift/restlessjar-9268',
    'https://fragment.com/gift/restlessjar-808',
    'https://fragment.com/gift/restlessjar-8000',
    'https://fragment.com/gift/restlessjar-45705',
    'https://fragment.com/gift/restlessjar-3345',
    'https://fragment.com/gift/restlessjar-3306',
    'https://fragment.com/gift/restlessjar-3222',
    'https://fragment.com/gift/restlessjar-26122',
    'https://fragment.com/gift/restlessjar-2375',
    'https://fragment.com/gift/restlessjar-21081',
    'https://fragment.com/gift/restlessjar-110',
    'https://fragment.com/gift/restlessjar-17861',
    'https://fragment.com/gift/restlessjar-65129',
    'https://fragment.com/gift/restlessjar-88088',
    'https://fragment.com/gift/faithamulet-55992',
    'https://fragment.com/gift/faithamulet-4441',
    'https://fragment.com/gift/faithamulet-35317',
    'https://fragment.com/gift/faithamulet-34357',
    'https://fragment.com/gift/faithamulet-33969',
    'https://fragment.com/gift/faithamulet-3337',
    'https://fragment.com/gift/faithamulet-2284',
    'https://fragment.com/gift/faithamulet-18094',
    'https://fragment.com/gift/faithamulet-1717',
    'https://fragment.com/gift/faithamulet-12384',
    'https://fragment.com/gift/faithamulet-111363',
    'https://fragment.com/gift/faithamulet-69114',
    'https://fragment.com/gift/faithamulet-83911',
    'https://fragment.com/gift/faithamulet-83198',
    'https://fragment.com/gift/faithamulet-53272',
    'https://fragment.com/gift/nailbracelet-378',
    'https://fragment.com/gift/nailbracelet-919',
    'https://fragment.com/gift/nailbracelet-4543',
    'https://fragment.com/gift/nailbracelet-3153',
    'https://fragment.com/gift/nailbracelet-3368',
    'https://fragment.com/gift/nailbracelet-638',
    'https://fragment.com/gift/nailbracelet-1010',
    'https://fragment.com/gift/nailbracelet-2871',
    'https://fragment.com/gift/nailbracelet-1535',
    'https://fragment.com/gift/nailbracelet-554',
    'https://fragment.com/gift/nailbracelet-3057',
    'https://fragment.com/gift/nailbracelet-917',
    'https://fragment.com/gift/nailbracelet-2194',
    'https://fragment.com/gift/nailbracelet-4279',
    'https://fragment.com/gift/nailbracelet-953',
    'https://fragment.com/gift/scaredcat-10792',
    'https://fragment.com/gift/scaredcat-4041',
    'https://fragment.com/gift/scaredcat-14058',
    'https://fragment.com/gift/scaredcat-2942',
    'https://fragment.com/gift/scaredcat-18319',
    'https://fragment.com/gift/scaredcat-15308',
    'https://fragment.com/gift/scaredcat-13810',
    'https://fragment.com/gift/scaredcat-10204',
    'https://fragment.com/gift/scaredcat-13300',
    'https://fragment.com/gift/scaredcat-16037',
    'https://fragment.com/gift/scaredcat-11162',
    'https://fragment.com/gift/scaredcat-11115',
    'https://fragment.com/gift/scaredcat-2249',
    'https://fragment.com/gift/scaredcat-1584',
    'https://fragment.com/gift/scaredcat-14428',
    'https://fragment.com/gift/winterwreath-22182',
    'https://fragment.com/gift/winterwreath-22021',
    'https://fragment.com/gift/winterwreath-1614',
    'https://fragment.com/gift/winterwreath-9889',
    'https://fragment.com/gift/winterwreath-37171',
    'https://fragment.com/gift/winterwreath-28317',
    'https://fragment.com/gift/winterwreath-27769',
    'https://fragment.com/gift/winterwreath-26654',
    'https://fragment.com/gift/winterwreath-24498',
    'https://fragment.com/gift/winterwreath-22178',
    'https://fragment.com/gift/winterwreath-20621',
    'https://fragment.com/gift/winterwreath-19957',
    'https://fragment.com/gift/winterwreath-14240',
    'https://fragment.com/gift/winterwreath-5409',
    'https://fragment.com/gift/winterwreath-23739',
    'https://fragment.com/gift/bowtie-6804',
    'https://fragment.com/gift/bowtie-642',
    'https://fragment.com/gift/bowtie-40660',
    'https://fragment.com/gift/bowtie-30338',
    'https://fragment.com/gift/bowtie-30223',
    'https://fragment.com/gift/bowtie-22847',
    'https://fragment.com/gift/bowtie-11888',
    'https://fragment.com/gift/bowtie-117',
    'https://fragment.com/gift/bowtie-5228',
    'https://fragment.com/gift/bowtie-43359',
    'https://fragment.com/gift/bowtie-20929',
    'https://fragment.com/gift/bowtie-19384',
    'https://fragment.com/gift/bowtie-18229',
    'https://fragment.com/gift/bowtie-16267',
    'https://fragment.com/gift/bowtie-10581',
    'https://fragment.com/gift/prettyposy-50914',
    'https://fragment.com/gift/prettyposy-4864',
    'https://fragment.com/gift/prettyposy-30955',
    'https://fragment.com/gift/prettyposy-24060',
    'https://fragment.com/gift/prettyposy-22326',
    'https://fragment.com/gift/prettyposy-22236',
    'https://fragment.com/gift/prettyposy-2059',
    'https://fragment.com/gift/prettyposy-40369',
    'https://fragment.com/gift/prettyposy-8574',
    'https://fragment.com/gift/prettyposy-8392',
    'https://fragment.com/gift/prettyposy-5345',
    'https://fragment.com/gift/prettyposy-48469',
    'https://fragment.com/gift/prettyposy-47573',
    'https://fragment.com/gift/prettyposy-45353',
    'https://fragment.com/gift/prettyposy-45350',
    'https://fragment.com/gift/diamondring-6815',
    'https://fragment.com/gift/diamondring-4614',
    'https://fragment.com/gift/diamondring-31487',
    'https://fragment.com/gift/diamondring-2806',
    'https://fragment.com/gift/diamondring-27870',
    'https://fragment.com/gift/diamondring-2672',
    'https://fragment.com/gift/diamondring-23178',
    'https://fragment.com/gift/diamondring-22737',
    'https://fragment.com/gift/diamondring-20760',
    'https://fragment.com/gift/diamondring-18415',
    'https://fragment.com/gift/diamondring-10973',
    'https://fragment.com/gift/diamondring-10208',
    'https://fragment.com/gift/diamondring-4650',
    'https://fragment.com/gift/diamondring-4834',
    'https://fragment.com/gift/diamondring-27772',
    'https://fragment.com/gift/trappedheart-11096',
    'https://fragment.com/gift/trappedheart-10097',
    'https://fragment.com/gift/trappedheart-7932',
    'https://fragment.com/gift/trappedheart-17151',
    'https://fragment.com/gift/trappedheart-59',
    'https://fragment.com/gift/trappedheart-16803',
    'https://fragment.com/gift/trappedheart-12526',
    'https://fragment.com/gift/trappedheart-7092',
    'https://fragment.com/gift/trappedheart-6926',
    'https://fragment.com/gift/trappedheart-4398',
    'https://fragment.com/gift/trappedheart-13252',
    'https://fragment.com/gift/trappedheart-11465',
    'https://fragment.com/gift/trappedheart-1163',
    'https://fragment.com/gift/trappedheart-2777',
    'https://fragment.com/gift/trappedheart-17590',
    'https://fragment.com/gift/mightyarm-2471',
    'https://fragment.com/gift/mightyarm-834',
    'https://fragment.com/gift/mightyarm-2928',
    'https://fragment.com/gift/mightyarm-3107',
    'https://fragment.com/gift/mightyarm-1178',
    'https://fragment.com/gift/mightyarm-174',
    'https://fragment.com/gift/mightyarm-3015',
    'https://fragment.com/gift/mightyarm-3120',
    'https://fragment.com/gift/mightyarm-1148',
    'https://fragment.com/gift/mightyarm-3101',
    'https://fragment.com/gift/mightyarm-175',
    'https://fragment.com/gift/mightyarm-940',
    'https://fragment.com/gift/mightyarm-3105',
    'https://fragment.com/gift/mightyarm-3114',
    'https://fragment.com/gift/mightyarm-1142',
    'https://fragment.com/gift/nekohelmet-5087',
    'https://fragment.com/gift/nekohelmet-4408',
    'https://fragment.com/gift/nekohelmet-4193',
    'https://fragment.com/gift/nekohelmet-2427',
    'https://fragment.com/gift/nekohelmet-1810',
    'https://fragment.com/gift/nekohelmet-1806',
    'https://fragment.com/gift/nekohelmet-11699',
    'https://fragment.com/gift/nekohelmet-10043',
    'https://fragment.com/gift/nekohelmet-4111',
    'https://fragment.com/gift/nekohelmet-8356',
    'https://fragment.com/gift/nekohelmet-14445',
    'https://fragment.com/gift/nekohelmet-14147',
    'https://fragment.com/gift/nekohelmet-10819',
    'https://fragment.com/gift/nekohelmet-4391',
    'https://fragment.com/gift/nekohelmet-208',
    'https://fragment.com/gift/witchhat-44551',
    'https://fragment.com/gift/witchhat-36054',
    'https://fragment.com/gift/witchhat-63046',
    'https://fragment.com/gift/witchhat-39688',
    'https://fragment.com/gift/witchhat-26091',
    'https://fragment.com/gift/witchhat-51412',
    'https://fragment.com/gift/witchhat-48012',
    'https://fragment.com/gift/witchhat-46761',
    'https://fragment.com/gift/witchhat-39412',
    'https://fragment.com/gift/witchhat-12759',
    'https://fragment.com/gift/witchhat-33410',
    'https://fragment.com/gift/witchhat-31710',
    'https://fragment.com/gift/witchhat-15343',
    'https://fragment.com/gift/witchhat-1120',
    'https://fragment.com/gift/witchhat-33',
    'https://fragment.com/gift/blingbinky-1069',
    'https://fragment.com/gift/blingbinky-1061',
    'https://fragment.com/gift/blingbinky-1282',
    'https://fragment.com/gift/blingbinky-755',
    'https://fragment.com/gift/blingbinky-571',
    'https://fragment.com/gift/blingbinky-4843',
    'https://fragment.com/gift/blingbinky-1687',
    'https://fragment.com/gift/blingbinky-1261',
    'https://fragment.com/gift/blingbinky-1234',
    'https://fragment.com/gift/blingbinky-1086',
    'https://fragment.com/gift/blingbinky-1077',
    'https://fragment.com/gift/blingbinky-4908',
    'https://fragment.com/gift/blingbinky-7807',
    'https://fragment.com/gift/blingbinky-6669',
    'https://fragment.com/gift/blingbinky-3562',
    'https://fragment.com/gift/easteregg-58770',
    'https://fragment.com/gift/easteregg-27464',
    'https://fragment.com/gift/easteregg-2288',
    'https://fragment.com/gift/easteregg-105367',
    'https://fragment.com/gift/easteregg-80415',
    'https://fragment.com/gift/easteregg-74372',
    'https://fragment.com/gift/easteregg-62081',
    'https://fragment.com/gift/easteregg-4448',
    'https://fragment.com/gift/easteregg-3721',
    'https://fragment.com/gift/easteregg-143334',
    'https://fragment.com/gift/easteregg-52373',
    'https://fragment.com/gift/easteregg-19124',
    'https://fragment.com/gift/easteregg-1721',
    'https://fragment.com/gift/easteregg-58028',
    'https://fragment.com/gift/easteregg-26517',
    'https://fragment.com/gift/jackinthebox-87525',
    'https://fragment.com/gift/jackinthebox-8565',
    'https://fragment.com/gift/jackinthebox-70358',
    'https://fragment.com/gift/jackinthebox-28421',
    'https://fragment.com/gift/jackinthebox-10806',
    'https://fragment.com/gift/jackinthebox-75286',
    'https://fragment.com/gift/jackinthebox-92252',
    'https://fragment.com/gift/jackinthebox-82674',
    'https://fragment.com/gift/jackinthebox-80402',
    'https://fragment.com/gift/jackinthebox-75786',
    'https://fragment.com/gift/jackinthebox-62828',
    'https://fragment.com/gift/jackinthebox-59919',
    'https://fragment.com/gift/jackinthebox-52602',
    'https://fragment.com/gift/jackinthebox-51425',
    'https://fragment.com/gift/jackinthebox-46668',
    'https://fragment.com/gift/lushbouquet-63328',
    'https://fragment.com/gift/lushbouquet-62166',
    'https://fragment.com/gift/lushbouquet-55775',
    'https://fragment.com/gift/lushbouquet-53912',
    'https://fragment.com/gift/lushbouquet-53751',
    'https://fragment.com/gift/lushbouquet-50000',
    'https://fragment.com/gift/lushbouquet-48349',
    'https://fragment.com/gift/lushbouquet-47170',
    'https://fragment.com/gift/lushbouquet-46503',
    'https://fragment.com/gift/lushbouquet-44728',
    'https://fragment.com/gift/lushbouquet-42455',
    'https://fragment.com/gift/lushbouquet-41794',
    'https://fragment.com/gift/lushbouquet-33084',
    'https://fragment.com/gift/lushbouquet-2685',
    'https://fragment.com/gift/lushbouquet-25350',
    'https://fragment.com/gift/bondedring-7258',
    'https://fragment.com/gift/bondedring-3671',
    'https://fragment.com/gift/bondedring-1072',
    'https://fragment.com/gift/bondedring-30',
    'https://fragment.com/gift/bondedring-6944',
    'https://fragment.com/gift/bondedring-5708',
    'https://fragment.com/gift/bondedring-438',
    'https://fragment.com/gift/bondedring-424',
    'https://fragment.com/gift/bondedring-3308',
    'https://fragment.com/gift/bondedring-2540',
    'https://fragment.com/gift/bondedring-1008',
    'https://fragment.com/gift/bondedring-7560',
    'https://fragment.com/gift/bondedring-6344',
    'https://fragment.com/gift/bondedring-5967',
    'https://fragment.com/gift/bondedring-4580',
    'https://fragment.com/gift/khabibspapakha-648',
    'https://fragment.com/gift/astralshard-3273',
    'https://fragment.com/gift/astralshard-3170',
    'https://fragment.com/gift/astralshard-4555',
    'https://fragment.com/gift/astralshard-3903',
    'https://fragment.com/gift/astralshard-3684',
    'https://fragment.com/gift/astralshard-3682',
    'https://fragment.com/gift/astralshard-3518',
    'https://fragment.com/gift/astralshard-3286',
    'https://fragment.com/gift/astralshard-189',
    'https://fragment.com/gift/astralshard-1093',
    'https://fragment.com/gift/astralshard-3362',
    'https://fragment.com/gift/astralshard-2663',
    'https://fragment.com/gift/astralshard-3642',
    'https://fragment.com/gift/astralshard-3515',
    'https://fragment.com/gift/astralshard-3339',
    'https://fragment.com/gift/flyingbroom-7219',
    'https://fragment.com/gift/flyingbroom-7194',
    'https://fragment.com/gift/flyingbroom-6758',
    'https://fragment.com/gift/flyingbroom-6421',
    'https://fragment.com/gift/flyingbroom-6183',
    'https://fragment.com/gift/flyingbroom-6160',
    'https://fragment.com/gift/flyingbroom-5251',
    'https://fragment.com/gift/flyingbroom-4044',
    'https://fragment.com/gift/flyingbroom-2637',
    'https://fragment.com/gift/flyingbroom-14182',
    'https://fragment.com/gift/flyingbroom-13279',
    'https://fragment.com/gift/flyingbroom-13028',
    'https://fragment.com/gift/flyingbroom-12918',
    'https://fragment.com/gift/flyingbroom-10901',
    'https://fragment.com/gift/flyingbroom-10466',
    'https://fragment.com/gift/heartlocket-1014',
    'https://fragment.com/gift/heartlocket-1012',
    'https://fragment.com/gift/heartlocket-1011',
    'https://fragment.com/gift/heartlocket-101',
    'https://fragment.com/gift/heartlocket-1007',
    'https://fragment.com/gift/heartlocket-1005',
    'https://fragment.com/gift/heartlocket-1003',
    'https://fragment.com/gift/heartlocket-1002',
    'https://fragment.com/gift/heartlocket-707',
    'https://fragment.com/gift/heartlocket-694',
    'https://fragment.com/gift/heartlocket-278',
    'https://fragment.com/gift/heartlocket-1465',
    'https://fragment.com/gift/heartlocket-803',
    'https://fragment.com/gift/heartlocket-1750',
    'https://fragment.com/gift/heartlocket-166',
    'https://fragment.com/gift/minioscar-3939',
    'https://fragment.com/gift/minioscar-462',
    'https://fragment.com/gift/minioscar-2945',
    'https://fragment.com/gift/minioscar-1013',
    'https://fragment.com/gift/minioscar-2872',
    'https://fragment.com/gift/minioscar-3609',
    'https://fragment.com/gift/minioscar-2915',
    'https://fragment.com/gift/minioscar-2927',
    'https://fragment.com/gift/minioscar-4002',
    'https://fragment.com/gift/minioscar-1815',
    'https://fragment.com/gift/minioscar-3223',
    'https://fragment.com/gift/minioscar-290',
    'https://fragment.com/gift/minioscar-2432',
    'https://fragment.com/gift/minioscar-352',
    'https://fragment.com/gift/minioscar-2900',
    'https://fragment.com/gift/skullflower-18916',
    'https://fragment.com/gift/skullflower-13703',
    'https://fragment.com/gift/skullflower-13584',
    'https://fragment.com/gift/skullflower-13303',
    'https://fragment.com/gift/skullflower-11072',
    'https://fragment.com/gift/skullflower-10820',
    'https://fragment.com/gift/skullflower-10600',
    'https://fragment.com/gift/skullflower-8174',
    'https://fragment.com/gift/skullflower-8173',
    'https://fragment.com/gift/skullflower-7779',
    'https://fragment.com/gift/skullflower-7767',
    'https://fragment.com/gift/skullflower-7760',
    'https://fragment.com/gift/skullflower-7666',
    'https://fragment.com/gift/skullflower-7640',
    'https://fragment.com/gift/skullflower-7616',
    'https://fragment.com/gift/moneypot-23984',
    'https://fragment.com/gift/moneypot-21623',
    'https://fragment.com/gift/moneypot-20017',
    'https://fragment.com/gift/moneypot-10832',
    'https://fragment.com/gift/moneypot-19808',
    'https://fragment.com/gift/moneypot-9103',
    'https://fragment.com/gift/moneypot-6100',
    'https://fragment.com/gift/moneypot-32517',
    'https://fragment.com/gift/moneypot-31151',
    'https://fragment.com/gift/moneypot-27101',
    'https://fragment.com/gift/moneypot-25505',
    'https://fragment.com/gift/moneypot-22324',
    'https://fragment.com/gift/moneypot-22185',
    'https://fragment.com/gift/moneypot-21659',
    'https://fragment.com/gift/moneypot-19951',
    'https://fragment.com/gift/snowglobe-1674',
    'https://fragment.com/gift/snowglobe-9666',
    'https://fragment.com/gift/snowglobe-5217',
    'https://fragment.com/gift/snowglobe-1777',
    'https://fragment.com/gift/snowglobe-8388',
    'https://fragment.com/gift/snowglobe-8264',
    'https://fragment.com/gift/snowglobe-7790',
    'https://fragment.com/gift/snowglobe-695',
    'https://fragment.com/gift/snowglobe-4418',
    'https://fragment.com/gift/snowglobe-3997',
    'https://fragment.com/gift/snowglobe-22929',
    'https://fragment.com/gift/snowglobe-14775',
    'https://fragment.com/gift/snowglobe-24377',
    'https://fragment.com/gift/snowglobe-14590',
    'https://fragment.com/gift/snowglobe-799',
    'https://fragment.com/gift/swagbag-143854',
    'https://fragment.com/gift/swagbag-120151',
    'https://fragment.com/gift/swagbag-76487',
    'https://fragment.com/gift/swagbag-60531',
    'https://fragment.com/gift/swagbag-172538',
    'https://fragment.com/gift/swagbag-125686',
    'https://fragment.com/gift/swagbag-82237',
    'https://fragment.com/gift/swagbag-60011',
    'https://fragment.com/gift/swagbag-226183',
    'https://fragment.com/gift/swagbag-187544',
    'https://fragment.com/gift/swagbag-185711',
    'https://fragment.com/gift/swagbag-15369',
    'https://fragment.com/gift/swagbag-12661',
    'https://fragment.com/gift/swagbag-12474',
    'https://fragment.com/gift/swagbag-123153',
    'https://fragment.com/gift/artisanbrick-4334',
    'https://fragment.com/gift/artisanbrick-4366',
    'https://fragment.com/gift/artisanbrick-4358',
    'https://fragment.com/gift/artisanbrick-3975',
    'https://fragment.com/gift/artisanbrick-4971',
    'https://fragment.com/gift/artisanbrick-58',
    'https://fragment.com/gift/artisanbrick-3808',
    'https://fragment.com/gift/artisanbrick-760',
    'https://fragment.com/gift/artisanbrick-4972',
    'https://fragment.com/gift/artisanbrick-3979',
    'https://fragment.com/gift/artisanbrick-4307',
    'https://fragment.com/gift/artisanbrick-3797',
    'https://fragment.com/gift/artisanbrick-4365',
    'https://fragment.com/gift/artisanbrick-4864',
    'https://fragment.com/gift/artisanbrick-4323',
    'https://fragment.com/gift/madpumpkin-4136',
    'https://fragment.com/gift/madpumpkin-2902',
    'https://fragment.com/gift/madpumpkin-1895',
    'https://fragment.com/gift/madpumpkin-10726',
    'https://fragment.com/gift/madpumpkin-8399',
    'https://fragment.com/gift/madpumpkin-6722',
    'https://fragment.com/gift/madpumpkin-6662',
    'https://fragment.com/gift/madpumpkin-612',
    'https://fragment.com/gift/madpumpkin-4347',
    'https://fragment.com/gift/madpumpkin-4169',
    'https://fragment.com/gift/madpumpkin-2551',
    'https://fragment.com/gift/madpumpkin-2271',
    'https://fragment.com/gift/madpumpkin-20',
    'https://fragment.com/gift/madpumpkin-190',
    'https://fragment.com/gift/madpumpkin-1318',
    'https://fragment.com/gift/plushpepe-1243',
    'https://fragment.com/gift/plushpepe-1404',
    'https://fragment.com/gift/plushpepe-1413',
    'https://fragment.com/gift/plushpepe-1576',
    'https://fragment.com/gift/plushpepe-1049',
    'https://fragment.com/gift/plushpepe-830',
    'https://fragment.com/gift/plushpepe-1479',
    'https://fragment.com/gift/plushpepe-583',
    'https://fragment.com/gift/plushpepe-495',
    'https://fragment.com/gift/plushpepe-1662',
    'https://fragment.com/gift/plushpepe-966',
    'https://fragment.com/gift/plushpepe-986',
    'https://fragment.com/gift/plushpepe-1468',
    'https://fragment.com/gift/plushpepe-989',
    'https://fragment.com/gift/plushpepe-2536',
    'https://fragment.com/gift/starnotepad-20772',
    'https://fragment.com/gift/starnotepad-15806',
    'https://fragment.com/gift/starnotepad-35049',
    'https://fragment.com/gift/starnotepad-27539',
    'https://fragment.com/gift/starnotepad-15283',
    'https://fragment.com/gift/starnotepad-61',
    'https://fragment.com/gift/starnotepad-57939',
    'https://fragment.com/gift/starnotepad-50196',
    'https://fragment.com/gift/starnotepad-47698',
    'https://fragment.com/gift/starnotepad-27491',
    'https://fragment.com/gift/starnotepad-23511',
    'https://fragment.com/gift/starnotepad-2000',
    'https://fragment.com/gift/starnotepad-12604',
    'https://fragment.com/gift/starnotepad-10992',
    'https://fragment.com/gift/starnotepad-1052',
    'https://fragment.com/gift/gemsignet-5519',
    'https://fragment.com/gift/gemsignet-13',
    'https://fragment.com/gift/gemsignet-1196',
    'https://fragment.com/gift/gemsignet-5189',
    'https://fragment.com/gift/gemsignet-655',
    'https://fragment.com/gift/gemsignet-651',
    'https://fragment.com/gift/gemsignet-1010',
    'https://fragment.com/gift/gemsignet-911',
    'https://fragment.com/gift/gemsignet-4269',
    'https://fragment.com/gift/gemsignet-5414',
    'https://fragment.com/gift/gemsignet-4222',
    'https://fragment.com/gift/gemsignet-5095',
    'https://fragment.com/gift/gemsignet-2832',
    'https://fragment.com/gift/gemsignet-538',
    'https://fragment.com/gift/gemsignet-871',
    'https://fragment.com/gift/jellybunny-36015',
    'https://fragment.com/gift/jellybunny-13794',
    'https://fragment.com/gift/jellybunny-13630',
    'https://fragment.com/gift/jellybunny-8969',
    'https://fragment.com/gift/jellybunny-65906',
    'https://fragment.com/gift/jellybunny-49982',
    'https://fragment.com/gift/jellybunny-38191',
    'https://fragment.com/gift/jellybunny-36663',
    'https://fragment.com/gift/jellybunny-36650',
    'https://fragment.com/gift/jellybunny-36317',
    'https://fragment.com/gift/jellybunny-3238',
    'https://fragment.com/gift/jellybunny-29173',
    'https://fragment.com/gift/jellybunny-27256',
    'https://fragment.com/gift/jellybunny-197',
    'https://fragment.com/gift/jellybunny-18592',
    'https://fragment.com/gift/berrybox-1136',
    'https://fragment.com/gift/berrybox-1133',
    'https://fragment.com/gift/berrybox-11016',
    'https://fragment.com/gift/berrybox-10992',
    'https://fragment.com/gift/berrybox-1062',
    'https://fragment.com/gift/berrybox-1027',
    'https://fragment.com/gift/berrybox-10050',
    'https://fragment.com/gift/berrybox-7148',
    'https://fragment.com/gift/berrybox-7052',
    'https://fragment.com/gift/berrybox-6014',
    'https://fragment.com/gift/berrybox-2739',
    'https://fragment.com/gift/berrybox-13633',
    'https://fragment.com/gift/berrybox-13967',
    'https://fragment.com/gift/berrybox-1036',
    'https://fragment.com/gift/berrybox-5733',
    'https://fragment.com/gift/kissedfrog-9862',
    'https://fragment.com/gift/kissedfrog-8686',
    'https://fragment.com/gift/kissedfrog-8209',
    'https://fragment.com/gift/kissedfrog-6297',
    'https://fragment.com/gift/kissedfrog-6292',
    'https://fragment.com/gift/kissedfrog-6164',
    'https://fragment.com/gift/kissedfrog-2342',
    'https://fragment.com/gift/kissedfrog-11421',
    'https://fragment.com/gift/kissedfrog-12121',
    'https://fragment.com/gift/kissedfrog-11449',
    'https://fragment.com/gift/kissedfrog-9841',
    'https://fragment.com/gift/kissedfrog-9798',
    'https://fragment.com/gift/kissedfrog-9775',
    'https://fragment.com/gift/kissedfrog-9763',
    'https://fragment.com/gift/kissedfrog-7876',
    'https://fragment.com/gift/joyfulbundle-870',
    'https://fragment.com/gift/joyfulbundle-8248',
    'https://fragment.com/gift/joyfulbundle-7464',
    'https://fragment.com/gift/joyfulbundle-66347',
    'https://fragment.com/gift/joyfulbundle-660',
    'https://fragment.com/gift/joyfulbundle-647',
    'https://fragment.com/gift/joyfulbundle-10099',
    'https://fragment.com/gift/joyfulbundle-885',
    'https://fragment.com/gift/joyfulbundle-32868',
    'https://fragment.com/gift/joyfulbundle-2455',
    'https://fragment.com/gift/joyfulbundle-23385',
    'https://fragment.com/gift/joyfulbundle-16126',
    'https://fragment.com/gift/joyfulbundle-1096',
    'https://fragment.com/gift/joyfulbundle-10804',
    'https://fragment.com/gift/joyfulbundle-10750',
    'https://fragment.com/gift/heroichelmet-452',
    'https://fragment.com/gift/heroichelmet-2901',
    'https://fragment.com/gift/heroichelmet-1177',
    'https://fragment.com/gift/heroichelmet-2892',
    'https://fragment.com/gift/heroichelmet-1178',
    'https://fragment.com/gift/heroichelmet-1207',
    'https://fragment.com/gift/heroichelmet-2660',
    'https://fragment.com/gift/heroichelmet-2331',
    'https://fragment.com/gift/heroichelmet-1658',
    'https://fragment.com/gift/heroichelmet-981',
    'https://fragment.com/gift/heroichelmet-6',
    'https://fragment.com/gift/heroichelmet-3004',
    'https://fragment.com/gift/heroichelmet-777',
    'https://fragment.com/gift/heroichelmet-2525',
    'https://fragment.com/gift/heroichelmet-1337',
    'https://fragment.com/gift/durovscap-2676',
    'https://fragment.com/gift/durovscap-152',
    'https://fragment.com/gift/durovscap-256',
    'https://fragment.com/gift/durovscap-1396',
    'https://fragment.com/gift/durovscap-2672',
    'https://fragment.com/gift/durovscap-4150',
    'https://fragment.com/gift/durovscap-2232',
    'https://fragment.com/gift/durovscap-3144',
    'https://fragment.com/gift/durovscap-1537',
    'https://fragment.com/gift/durovscap-203',
    'https://fragment.com/gift/durovscap-1010',
    'https://fragment.com/gift/durovscap-1853',
    'https://fragment.com/gift/durovscap-1379',
    'https://fragment.com/gift/durovscap-2688',
    'https://fragment.com/gift/durovscap-832',
    'https://fragment.com/gift/eternalrose-20012',
    'https://fragment.com/gift/eternalrose-1676',
    'https://fragment.com/gift/eternalrose-18516',
    'https://fragment.com/gift/eternalrose-8885',
    'https://fragment.com/gift/eternalrose-726',
    'https://fragment.com/gift/eternalrose-6649',
    'https://fragment.com/gift/eternalrose-27415',
    'https://fragment.com/gift/eternalrose-17453',
    'https://fragment.com/gift/eternalrose-1443',
    'https://fragment.com/gift/eternalrose-4288',
    'https://fragment.com/gift/eternalrose-7063',
    'https://fragment.com/gift/eternalrose-9631',
    'https://fragment.com/gift/eternalrose-7680',
    'https://fragment.com/gift/eternalrose-3976',
    'https://fragment.com/gift/eternalrose-14241',
    'https://fragment.com/gift/bdaycandle-193140',
    'https://fragment.com/gift/bdaycandle-171821',
    'https://fragment.com/gift/bdaycandle-1335',
    'https://fragment.com/gift/bdaycandle-10973',
    'https://fragment.com/gift/bdaycandle-94073',
    'https://fragment.com/gift/bdaycandle-80475',
    'https://fragment.com/gift/bdaycandle-56843',
    'https://fragment.com/gift/bdaycandle-102346',
    'https://fragment.com/gift/bdaycandle-96375',
    'https://fragment.com/gift/bdaycandle-90817',
    'https://fragment.com/gift/bdaycandle-65724',
    'https://fragment.com/gift/bdaycandle-5563',
    'https://fragment.com/gift/bdaycandle-34703',
    'https://fragment.com/gift/bdaycandle-27424',
    'https://fragment.com/gift/bdaycandle-249657',
    'https://fragment.com/gift/bigyear-57188',
    'https://fragment.com/gift/bigyear-417',
    'https://fragment.com/gift/bigyear-35015',
    'https://fragment.com/gift/bigyear-23619',
    'https://fragment.com/gift/bigyear-19331',
    'https://fragment.com/gift/bigyear-13160',
    'https://fragment.com/gift/bigyear-51602',
    'https://fragment.com/gift/bigyear-40611',
    'https://fragment.com/gift/bigyear-33618',
    'https://fragment.com/gift/bigyear-23368',
    'https://fragment.com/gift/bigyear-17645',
    'https://fragment.com/gift/bigyear-20181',
    'https://fragment.com/gift/bigyear-15034',
    'https://fragment.com/gift/bigyear-11574',
    'https://fragment.com/gift/bigyear-3480',
    'https://fragment.com/gift/candycane-10434',
    'https://fragment.com/gift/candycane-99511',
    'https://fragment.com/gift/candycane-89999',
    'https://fragment.com/gift/candycane-76869',
    'https://fragment.com/gift/candycane-46046',
    'https://fragment.com/gift/candycane-59725',
    'https://fragment.com/gift/candycane-41241',
    'https://fragment.com/gift/candycane-32140',
    'https://fragment.com/gift/candycane-56871',
    'https://fragment.com/gift/candycane-48880',
    'https://fragment.com/gift/candycane-111914',
    'https://fragment.com/gift/candycane-89848',
    'https://fragment.com/gift/candycane-8104',
    'https://fragment.com/gift/candycane-57977',
    'https://fragment.com/gift/candycane-4947',
    'https://fragment.com/gift/evileye-22020',
    'https://fragment.com/gift/evileye-20493',
    'https://fragment.com/gift/evileye-20000',
    'https://fragment.com/gift/evileye-16406',
    'https://fragment.com/gift/evileye-16143',
    'https://fragment.com/gift/evileye-2062',
    'https://fragment.com/gift/evileye-68998',
    'https://fragment.com/gift/evileye-19386',
    'https://fragment.com/gift/evileye-54461',
    'https://fragment.com/gift/evileye-4480',
    'https://fragment.com/gift/evileye-28940',
    'https://fragment.com/gift/evileye-22722',
    'https://fragment.com/gift/evileye-2271',
    'https://fragment.com/gift/evileye-2236',
    'https://fragment.com/gift/evileye-13525'
];

window.NFT_NAMES = {
    'toybear': 'Toy Bear',
    'artisanbrick': 'Artisan Brick',
    'astralshard': 'Astral Shard',
    'bdaycandle': 'Bday Candle',
    'berrybox': 'Berry Box',
    'bigyear': 'Big Year',
    'bondedring': 'Bonded Ring',
    'bowtie': 'Bow Tie',
    'bunnymuffin': 'Bunny Muffin',
    'candycane': 'Candy Cane',
    'cloverpin': 'Clover Pin',
    'cookieheart': 'Cookie Heart',
    'crystalball': 'Crystal Ball',
    'cupidcharm': 'Cupid Charm',
    'deskcalendar': 'Desk Calendar',
    'diamondring': 'Diamond Ring',
    'durovscap': 'Durovs Cap',
    'easteregg': 'Easter Egg',
    'electricskull': 'Electric Skull',
    'eternalcandle': 'Eternal Candle',
    'eternalrose': 'Eternal Rose',
    'evileye': 'Evil Eye',
    'faithamulet': 'Faith Amulet',
    'flyingbroom': 'Flying Broom',
    'freshsocks': 'Fresh Socks',
    'gemsignet': 'Gem Signet',
    'genielamp': 'Genie Lamp',
    'gingercookie': 'Ginger Cookie',
    'hangingstar': 'Hanging Star',
    'happybrownie': 'Happy Brownie',
    'heartlocket': 'Heart Locket',
    'heroichelmet': 'Heroic Helmet',
    'hexpot': 'Hex Pot',
    'holidaydrink': 'Holiday Drink',
    'homemadecake': 'Homemade Cake',
    'hypnolollipop': 'Hypno Lollipop',
    'icecream': 'Ice Cream',
    'inputkey': 'Input Key',
    'instantramen': 'Instant Ramen',
    'iongem': 'Ion Gem',
    'ionicdryer': 'Ionic Dryer',
    'jackinthebox': 'Jack In The Box',
    'jellybunny': 'Jelly Bunny',
    'jesterhat': 'Jester Hat',
    'jinglebells': 'Jingle Bells',
    'jollychimp': 'Jolly Chimp',
    'joyfulbundle': 'Joyful Bundle',
    'kissedfrog': 'Kissed Frog',
    'lightsword': 'Light Sword',
    'lolpop': 'Lol Pop',
    'lootbag': 'Loot Bag',
    'lovecandle': 'Love Candle',
    'lovepotion': 'Love Potion',
    'lowrider': 'Low Rider',
    'lunarsnake': 'Lunar Snake',
    'lushbouquet': 'Lush Bouquet',
    'madpumpkin': 'Mad Pumpkin',
    'magicpotion': 'Magic Potion',
    'mightyarm': 'Mighty Arm',
    'minioscar': 'Mini Oscar',
    'moonpendant': 'Moon Pendant',
    'moussecake': 'Mousse Cake',
    'nailbracelet': 'Nail Bracelet',
    'nekohelmet': 'Neko Helmet',
    'partysparkler': 'Party Sparkler',
    'perfumebottle': 'Perfume Bottle',
    'petsnake': 'Pet Snake',
    'plushpepe': 'Plush Pepe',
    'preciouspeach': 'Precious Peach',
    'recordplayer': 'Record Player',
    'restlessjar': 'Restless Jar',
    'sakuraflower': 'Sakura Flower',
    'santahat': 'Santa Hat',
    'sharptongue': 'Sharp Tongue',
    'scaredcat': 'Scared Cat',
    'signetring': 'Signet Ring',
    'skullflower': 'Skull Flower',
    'skystilettos': 'Sky Stilettos',
    'sleighbell': 'Sleigh Bell',
    'snakebox': 'Snake Box',
    'snoopcigar': 'Snoop Cigar',
    'snoopdogg': 'Snoop Dogg',
    'snowglobe': 'Snow Globe',
    'snowmittens': 'Snow Mittens',
    'spicedwine': 'Spiced Wine',
    'springbasket': 'Spring Basket',
    'spyagaric': 'Spy Agaric',
    'starnotepad': 'Star Notepad',
    'stellarrocket': 'Stellar Rocket',
    'swagbag': 'Swag Bag',
    'swisswatch': 'Swiss Watch',
    'tamagadget': 'Tama Gadget',
    'tophat': 'Top Hat',
    'trappedheart': 'Trapped Heart',
    'valentinebox': 'Valentine Box',
    'vintagecigar': 'Vintage Cigar',
    'voodoodoll': 'Voodoo Doll',
    'westsidesign': 'Westside Design',
    'whipcupcake': 'Whip Cupcake',
    'winterwreath': 'Winter Wreath',
    'witchhat': 'Witch Hat',
    'xmasstocking': 'Xmas Stocking'
};

window.NFT_COLLECTION_PRICES = {
    "inputkey": 4.03,
    "artisanbrick": 60.5,
    "mightyarm": 155,
    "plushpepe": 5630,
    "heroichelmet": 201.99,
    "durovscap": 685,
    "toybear": 24.68,
    "preciouspeach": 305,
    "lootbag": 83.4,
    "jollychimp": 4.92,
    "swisswatch": 38.74,
    "snoopdogg": 3.1,
    "lowrider": 30.79,
    "nailbracelet": 99.99,
    "snoopcigar": 8.5,
    "vintagecigar": 25.6,
    "iongem": 68.24,
    "stellarrocket": 2.89,
    "cupidcharm": 13.95,
    "genielamp": 38.33,
    "ionicdryer": 13.43,
    "signetring": 27.93,
    "scaredcat": 63.99,
    "diamondring": 21.39,
    "nekohelmet": 28.86,
    "bondedring": 42.49,
    "astralshard": 135.9,
    "swagbag": 3.44,
    "kissedfrog": 33.99,
    "gemsignet": 52.2,
    "madpumpkin": 13.4,
    "eternalrose": 18.49,
    "petsnake": 2.35,
    "lolpop": 2.3,
    "electricskull": 26.97,
    "whipcupcake": 2.17,
    "voodoodoll": 22.76,
    "magicpotion": 60,
    "deskcalendar": 2.2,
    "tophat": 8.69,
    "moonpendant": 2.99,
    "perfumebottle": 71,
    "sharptongue": 34.99,
    "lightsword": 4.1,
    "lovepotion": 10.78,
    "sakuraflower": 6.02,
    "lunarsnake": 2.16,
    "westsidesign": 59.87,
    "restlessjar": 3.51,
    "bowtie": 3.6,
    "easteregg": 3.09,
    "lushbouquet": 3.72,
    "heartlocket": 974.99,
    "minioscar": 74.9,
    "snowglobe": 4.24,
    "jellybunny": 4.7,
    "bdaycandle": 2.2,
    "evileye": 4.89,
    "candycane": 2.25,
    "lovecandle": 7.99,
    "snakebox": 2.19,
    "hangingstar": 5.37,
    "crystalball": 8.77,
    "tamagadget": 2.95,
    "bunnymuffin": 4.3,
    "gingercookie": 2.67,
    "xmasstocking": 2.24,
    "jesterhat": 2.4,
    "spyagaric": 4.56,
    "valentinebox": 6.5,
    "eternalcandle": 4.21,
    "partysparkler": 2.53,
    "recordplayer": 8.56,
    "sleighbell": 7.3,
    "cookieheart": 2.52,
    "trappedheart": 9.94,
    "winterwreath": 2.91,
    "jackinthebox": 3.26,
    "witchhat": 3.97,
    "skullflower": 8.81,
    "flyingbroom": 8.36,
    "starnotepad": 2.88,
    "berrybox": 4.8,
    "joyfulbundle": 3.55,
    "bigyear": 2.82,
    "homemadecake": 2.7,
    "santahat": 4.1,
    "hexpot": 3.48,
    "freshsocks": 2.57,
    "jinglebells": 2.89,
    "spicedwine": 2.71,
    "hypnolollipop": 2.89,
    "snowmittens": 4.24,
    "holidaydrink": 2.4,
    "skystilettos": 7.1,
    "cloverpin": 2.54,
    "springbasket": 3.38,
    "happybrownie": 2.42,
    "instantramen": 2.16,
    "moussecake": 2.8,
    "icecream": 2.17,
    "faithamulet": 2.5,
    "prettyposy": 2.64,
    "blingbinky": 23.49,
    "khabibspapakha": 50,
    "moneypot": 2.77
};